name: Python Workflow Demo

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Building the Code
        run: echo "Building the Code"

  Execute:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Python Version
        run: python -V
      - name: Identifying the Folder
        run: pwd
      - name: List the files in the folder
        run: ls
      - name: Run Python File
        run: python hello.py
